aliases = {
    'corrected_year': 'Incident Year',
    'IMO': 'Incident Month',
    'DATE': 'Date',
    'RAILROAD': 'Reporting Railroad Code',
    'CARS': 'Hazmat Cars Involved',
    'CARSDMG': 'Hazmat Cars Damaged/Derailed',
    'CARSHZD': 'Hazmat Cars Released',
    'EVACUATE': 'Persons Evacuated',
    'TEMP': 'Temperature',
    'VISIBILITY': 'Visibility Code',
    'WEATHER': 'Weather Condition Code',
    'TRNSPD': 'Train Speed (mph)',
    'TONS': 'Trailing Tons',
    'LOADF1': 'Loaded Freight Cars',
    'LOADP1': 'Loaded Passenger Cars',
    'EMPTYF1': 'Empty Freight Cars',
    'EMPTYP1': 'Empty Passenger Cars',
    'LOADF2': 'Derailed Loaded Freight Cars',
    'LOADP2': 'Derailed Loaded Passenger Cars',
    'EMPTYF2': 'Derailed Empty Freight Cars',
    'EMPTYP2': 'Derailed Empty Passenger Cars',
    'ACCDMG': 'Total Damage Cost',
    'EQPDMG': 'Equipment Damage Cost',
    'TRKDMG': 'Track Damage Cost',
    'TOTINJ': 'Total Injuries',
    'TOTKLD': 'Total Fatalities',
    'ENGRS': 'Engineers on Duty',
    'FIREMEN': 'Firemen on Duty',
    'CONDUCTR': 'Conductors on Duty',
    'BRAKEMEN': 'Brakemen on Duty',
    'ALCOHOL': 'Positive Alcohol Tests',
    'DRUG': 'Positive Drug Tests',
}